### ISSUE TITLE
Gymnasium isn't OpenAI Gym :)

### ISSUE THREAD

**Issue by jkterry1** [amacati/SoulsGym#46]
Hey,

I run the Farama Foundation (the maintainers of Gymnasium) and I used to maintain OpenAI gym. You use Gymnasium, but your readme says you use OpenAI Gym. Could you please say Gymnasium instead? Gymnasium and OpenAI Gym aren't the same thing, and OpenAI has no involvement in these things anymore.

**Comment by amacati** [comment]
Hi,

You are right, sorry for that. I was actually using gym for most of the development and switched to Gymnasium rather recently (commit c8a7464) when I saw that Farama has taken over the development. I will change that asap.

Thanks btw for the work with gymnasium. The new checks forced me to reorganize my spaces, but they are also way better now because of that. How did you find this niche repository btw? :D
